#!/usr/bin/env sh
# -*- coding: utf-8 -*-

cd sonospy
python pycpoint.py "$@" >../pycpoint.log 2>&1 &
echo $! >../pycpoint.pid

cd ..
python web2py/web2py.py -L options.py >web2py.log 2>&1 &
echo $! >web2py.pid
