#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from gluon.import_all import base_modules, contributed_modules

setup(app=['web2py.py'],
      data_files=[
        'admin.w2p',
        'examples.w2p',
        'welcome.w2p',
        'ABOUT',
        'LICENSE',
        'VERSION',
        ],
      options={'py2app': {
            'argv_emulation': True,
            'includes': base_modules,
            'packages': contributed_modules,
            }},
      setup_requires=['py2app'])
